First Codereview
ethernalwave/sprint-1 pull request #4
Opened 2022-11-24 17:52 UTC by ethernalwave

First Codereview reverted

2022-11-29 18:13 UTC, MarkFialko reviewed
Файла .DS_Store в гите быть не должно. Форматирование файлов
(option + command + L ), поправить отступы. У ссылки нет ховера.

2022-11-29 18:13 UTC, MarkFialko commented on README.md
> -
Удалил README?

2022-11-29 18:13 UTC, MarkFialko commented on blocks/header/header.css
> -
Форматирование

2022-11-29 18:13 UTC, MarkFialko commented on blocks/rotation/rotation.css
> +  }
Форматирование

2022-11-29 18:13 UTC, MarkFialko commented on pages/index.css
Форматирование

2022-11-29 18:16 UTC, MarkFialko requested changes
Переделать вёрстку, добавить интерактивность на ссылки

2022-11-29 18:18 UTC, MarkFialko commented
![Uploading Снимок экрана 2022-11-29 в 23.10.01.png…]()

2022-11-29 18:19 UTC, MarkFialko commented on pages/index.css
![Снимок экрана 2022-11-29 в 23 10 01](https://user-images.githubusercontent.com/91086103/204613583-da58ad74-ee37-4f84-83c4-9a4550e8cde9.png)
Добавить ховер на ссылку

2022-11-29 18:19 UTC, MarkFialko commented on pages/index.css
Отступы
![Снимок экрана 2022-11-29 в 23 09 43](https://user-images.githubusercontent.com/91086103/204613685-eba7e1e4-e77c-4441-84a2-6c196b2b52f0.png)

2022-11-30 13:43 UTC, Kuzuru requested changes

2022-11-30 13:43 UTC, Kuzuru commented on index.html
> +        <img class="feynman__img" src="./images/feyman/feynman.png">
Почему удалён `alt`?

2022-11-30 13:43 UTC, Kuzuru commented on pages/index.css
Отсутствует визуальное разделение (пустая строка) по блокам

2022-12-07 05:36 UTC, ethernalwave commented on pages/index.css
С отступами все отлично, так и указано в первом спринте

2022-12-10 14:34 UTC, merged